version: '3.8'
services:
    ruby:
        container_name: vsnippet-ssti-classic-erb-42
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:1337
